openapi: 3.1.0
info:
  title: API Contrôle des opérations de rénovation énergétique
  version: 1.0.0
  contact:
    name: Adrien Rosi Dit Rozzi
    email: adrienrosi@gmail.com
servers:
  - url: /
security:
  - apiKey: []
tags:
  - name: Opérations à contrôler
  - name: Contrôles
  - name: Organismes de contrôle
paths:
  /lots:
    get:
      summary: Recherche des lots d'opération à contrôler
      tags: [Opérations à contrôler]
      operationId: searchLots
    post:
      summary: Créé un nouveau lot d'opérations à contrôler
      tags: [Opérations à contrôler]
      operationId: createLot
  /lots/{lot_uuid}:
    get:
      summary: Cherche un lot d'opérations à contrôler
      description: Retourne un lot d'opérations à contrôler à partir de son identifiant
      tags: [Opérations à contrôler]
      operationId: findLot
    delete:
      summary: Supprime un lot d'opérations à contrôler
      tags: [Opérations à contrôler]
      operationId: removeLot
  /lots/{lot_uuid}/affecte/{organisme_controle_uuid}:
    patch:
      summary: Affecte un lot d'opérations à contrôler à un organisme de contrôle
      tags: [Opérations à contrôler]
      operationId: applyOrganismeControle
  /lots/{lot_uuid}/mesures_correctives:
    post:
      summary: Transmet une liste de mesures correctives effectuées
      tags: [Opérations à contrôler]
      operationId: addMesuresCorrectives
  /lots/{lot_uuid}/controle/synthese:
    post:
      summary: Transmet le document de synthèse des contrôles effectués au format PDF
      description: Si un document de synthèse existe déjà, il est remplacé par le nouveau document.
      tags: [Contrôles]
      operationId: postSynthese
    delete:
      summary: Supprime le document de synthèse des contrôles effectués
      tags: [Contrôles]
      operationId: removeSynthese
  /lots/{lot_uuid}/controle/non_conformites:
    post:
      summary: Transmet une liste des non-conformités constatées lors des contrôles
      tags: [Contrôles]
      operationId: addNonConformites
    delete:
      summary: Supprime la liste des non-conformités
      tags: [Contrôles]
      operationId: removeNonConformites
components:
  schemas:
    typeNonConformite:
      title: Type de non-conformité
      type: string
      oneOf:
        - const: majeur
          title: Majeure
        - const: mineure
          title: Mineure
    categorieNonConformite:
      title: Catégorie de non-conformité
      type: string
      oneOf:
        - const: quantite
          title: Problème de quantité
        - const: performance
          title: Problème de performance technique
        - const: regles_art
          title: Non respect des règles de l'art
        - const: securite_occupants
          title: Sécurité des occupants
        - const: administratif
          title: Non conformité des pièces administratives
    nonConformite:
      title: Non-conformité constatée lors d'un contrôle
      type: object
      properties:
